version: '3.5'

networks:
  ip6:

services:
  redis:
    container_name: grpc_redis
    restart: always
    image: redis
    networks:
      - ip6

  grpc_server:
    container_name: grpc_server
    restart: always
    environment:
      - LEADERBOARD_PAGE_SIZE=3
      - GRPC_SERVER_PORT=[::]:50051
      - GRPC_SERVER_WORKERS=3
      - REDIS_HOST=0.0.0.0
#    command: >
#      bash cron_script.sh
    volumes:
      - .:/rpc_server
    build:
      context: ./rpc_server
      dockerfile: Dockerfile
    networks:
      - ip6
    depends_on:
      - redis

  grpc_client:
    container_name: grpc_client
    restart: always
    environment:
      - GRPC_SERVER_PORT=[::]:50051
      - FLASK_PORT=5000
    volumes:
      - .:/rpc_client
    build:
      context: ./rpc_client
      dockerfile: Dockerfile
#    command: >
#      uwsgi
#      --module client:app
#      --master
#      --processes=5
#      --threads=4
#      --buffer-size=32768
#      --http=0.0.0.0:5000
#      --vacuum
#      --die-on-term
#      --lazy-apps
    ports:
      - 5000:5000
    networks:
      - ip6
    depends_on:
      - redis
      - grpc_server
