version: '3'

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    networks:
      - lan

  server:
    container_name: server
    restart: always
    environment:
      - REDIS_HOST=redis
#    command: >
#      bash cron_script.sh
    build:
      context: .
      dockerfile: server-dockerfile
    command: >
      bash -c "python3 server.py"
    depends_on:
      - redis
    networks:
      - lan

  client:
    container_name: client
    restart: always
    build:
      context: .
      dockerfile: client-dockerfile
    command: >
      bash -c "python3 client.py"
    environment:
      - GRPC_SERVER_HOST=server:50051    # must be the name of the container + port !
    ports:
      - 5000:5000
    depends_on:
      - redis
      - server
    networks:
      - lan

networks:
  lan:
