version: '3.5'
#
#networks:
#  ip6

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: always
#    networks:
#      - ip6

  server:
    restart: always
    environment:
      - REDIS_HOST=redis
#    command: >
#      bash cron_script.sh
    volumes:
      - .:/rpc_server
    build:
      context: .
      dockerfile: server-dockerfile
    command: >
      bash -c "python3 server.py"
#    networks:
#      - ip6
    depends_on:
      - redis

  client:
    restart: always
    environment:
      - GRPC_SERVER_HOST=server
    build:
      context: .
      dockerfile: client-dockerfile
    command: >
      bash -c "python3 client.py"
    ports:
      - 5000:5000
#    networks:
#      - ip6
    depends_on:
      - redis
      - server
