version: '3'

services:
  redis:
    image: redis
    restart: always

  server:
    restart: always
    environment:
      - REDIS_HOST=redis
#    command: >
#      bash cron_script.sh
    build:
      context: .
      dockerfile: server-dockerfile
    command: >
      bash -c "python3 server.py"
    ports:
      - "50051:50051"
    depends_on:
      - redis

  client:
    restart: always
    build:
      context: .
      dockerfile: client-dockerfile
    command: >
      bash -c "python3 client.py"
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - server
