version: '3.5'

networks:
  ip6:

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: always
    networks:
      - ip6

  server:
    restart: always
    environment:
      - REDIS_HOST=redis
#      - LEADERBOARD_PAGE_SIZE=3
#      - GRPC_SERVER_PORT=[::]:50051
#      - GRPC_SERVER_WORKERS=3
#    command: >
#      bash cron_script.sh
#    volumes:
#      - .:/rpc_server
    build:
      context: .
      dockerfile: server-dockerfile
    command: >
      bash -c "python3 server.py"
    networks:
      - ip6
    depends_on:
      - redis

  client:
    restart: always
#    environment:
#      - GRPC_SERVER_PORT=[::]:50051
#      - FLASK_PORT=5000
#    volumes:
#      - .:/rpc_client
    build:
      context: .
      dockerfile: client-dockerfile
    command: >
      bash -c "python3 client.py"

#    command: >
#      uwsgi
#      --module client:app
#      --master
#      --processes=5
#      --threads=4
#      --buffer-size=32768
#      --http=0.0.0.0:5000
#      --vacuum
#      --die-on-term
#      --lazy-apps
    ports:
      - 5000:5000
    networks:
      - ip6
    depends_on:
      - redis
      - server
